version: '3'

services:
    app:
        image: 'hermeto/nodemon:latest'
        container_name: 'alura'
        networks:
            - 'network'
        volumes:
            - '.:/app'
        ports:
            - '3000:3000'
        depends_on:
            - 'db'
        command: 'nodemon server'
    db:
        image: 'mysql:latest'
        container_name: 'alura-database'
        networks:
            - 'network'
        volumes:
            - '/dev/shm/mysql/alura:/var/lib/mysql'
        environment:
            - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'

networks:
    network:
        driver: 'bridge'
