version: "3"
services:
    app:
        image: "hermeto/opfox:1.0"
        container_name: "app"
        networks:
            - "network"
        volumes:
            - ".:/var/www/html"
        ports:
            - "80:80"
        depends_on:
            - "db"
    db:
        image: "hermeto/opfox-db:1.0"
        container_name: "app-db"
        networks:
            - "network"
        volumes:
            - "/dev/shm/mysql:/var/lib/mysql"
        environment:
            - "MYSQL_ROOT_PASSWORD=chayote"
            - "MYSQL_DATABASE=vegetables"
networks:
    network:
        driver: "bridge"
