php:
  build: "./php"
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - "./www:/var/www/html/"
  links:
   - "db"
db:
  build: "./mysql"
  volumes:
   - "/var/lib/mysql/"
  environment:
   - "MYSQL_ROOT_PASSWORD=chayote"
   - "MYSQL_DATABASE=vegetables"
